// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isDurosNodeInfo_JournalDeviceInfo is an autogenerated mock type for the isDurosNodeInfo_JournalDeviceInfo type
type isDurosNodeInfo_JournalDeviceInfo struct {
	mock.Mock
}

// isDurosNodeInfo_JournalDeviceInfo provides a mock function with no fields
func (_m *isDurosNodeInfo_JournalDeviceInfo) isDurosNodeInfo_JournalDeviceInfo() {
	_m.Called()
}

// newIsDurosNodeInfo_JournalDeviceInfo creates a new instance of isDurosNodeInfo_JournalDeviceInfo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsDurosNodeInfo_JournalDeviceInfo(t interface {
	mock.TestingT
	Cleanup(func())
}) *isDurosNodeInfo_JournalDeviceInfo {
	mock := &isDurosNodeInfo_JournalDeviceInfo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
