// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isPolicy_Info is an autogenerated mock type for the isPolicy_Info type
type isPolicy_Info struct {
	mock.Mock
}

// isPolicy_Info provides a mock function with no fields
func (_m *isPolicy_Info) isPolicy_Info() {
	_m.Called()
}

// newIsPolicy_Info creates a new instance of isPolicy_Info. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsPolicy_Info(t interface {
	mock.TestingT
	Cleanup(func())
}) *isPolicy_Info {
	mock := &isPolicy_Info{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
