// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// isPolicy_Info is an autogenerated mock type for the isPolicy_Info type
type isPolicy_Info struct {
	mock.Mock
}

// isPolicy_Info provides a mock function with given fields:
func (_m *isPolicy_Info) isPolicy_Info() {
	_m.Called()
}

// newIsPolicy_Info creates a new instance of isPolicy_Info. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func newIsPolicy_Info(t testing.TB) *isPolicy_Info {
	mock := &isPolicy_Info{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
