// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// isSchedulePolicy_SchedulePolicies is an autogenerated mock type for the isSchedulePolicy_SchedulePolicies type
type isSchedulePolicy_SchedulePolicies struct {
	mock.Mock
}

// isSchedulePolicy_SchedulePolicies provides a mock function with given fields:
func (_m *isSchedulePolicy_SchedulePolicies) isSchedulePolicy_SchedulePolicies() {
	_m.Called()
}

// newIsSchedulePolicy_SchedulePolicies creates a new instance of isSchedulePolicy_SchedulePolicies. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func newIsSchedulePolicy_SchedulePolicies(t testing.TB) *isSchedulePolicy_SchedulePolicies {
	mock := &isSchedulePolicy_SchedulePolicies{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
