// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isSchedulePolicy_SchedulePolicies is an autogenerated mock type for the isSchedulePolicy_SchedulePolicies type
type isSchedulePolicy_SchedulePolicies struct {
	mock.Mock
}

// isSchedulePolicy_SchedulePolicies provides a mock function with given fields:
func (_m *isSchedulePolicy_SchedulePolicies) isSchedulePolicy_SchedulePolicies() {
	_m.Called()
}

type mockConstructorTestingTnewIsSchedulePolicy_SchedulePolicies interface {
	mock.TestingT
	Cleanup(func())
}

// newIsSchedulePolicy_SchedulePolicies creates a new instance of isSchedulePolicy_SchedulePolicies. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newIsSchedulePolicy_SchedulePolicies(t mockConstructorTestingTnewIsSchedulePolicy_SchedulePolicies) *isSchedulePolicy_SchedulePolicies {
	mock := &isSchedulePolicy_SchedulePolicies{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
