// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isUpdatePolicyRequest_Policy is an autogenerated mock type for the isUpdatePolicyRequest_Policy type
type isUpdatePolicyRequest_Policy struct {
	mock.Mock
}

// isUpdatePolicyRequest_Policy provides a mock function with given fields:
func (_m *isUpdatePolicyRequest_Policy) isUpdatePolicyRequest_Policy() {
	_m.Called()
}

// newIsUpdatePolicyRequest_Policy creates a new instance of isUpdatePolicyRequest_Policy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsUpdatePolicyRequest_Policy(t interface {
	mock.TestingT
	Cleanup(func())
}) *isUpdatePolicyRequest_Policy {
	mock := &isUpdatePolicyRequest_Policy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
