// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isUpdateVolumeRequest_QosPolicyID is an autogenerated mock type for the isUpdateVolumeRequest_QosPolicyID type
type isUpdateVolumeRequest_QosPolicyID struct {
	mock.Mock
}

// isUpdateVolumeRequest_QosPolicyID provides a mock function with no fields
func (_m *isUpdateVolumeRequest_QosPolicyID) isUpdateVolumeRequest_QosPolicyID() {
	_m.Called()
}

// newIsUpdateVolumeRequest_QosPolicyID creates a new instance of isUpdateVolumeRequest_QosPolicyID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsUpdateVolumeRequest_QosPolicyID(t interface {
	mock.TestingT
	Cleanup(func())
}) *isUpdateVolumeRequest_QosPolicyID {
	mock := &isUpdateVolumeRequest_QosPolicyID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
