// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isWorkflow_Input is an autogenerated mock type for the isWorkflow_Input type
type isWorkflow_Input struct {
	mock.Mock
}

// isWorkflow_Input provides a mock function with no fields
func (_m *isWorkflow_Input) isWorkflow_Input() {
	_m.Called()
}

// newIsWorkflow_Input creates a new instance of isWorkflow_Input. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsWorkflow_Input(t interface {
	mock.TestingT
	Cleanup(func())
}) *isWorkflow_Input {
	mock := &isWorkflow_Input{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
