// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: lightbits/api/duros/v2/proxy_info.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProxyInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL
	//
	// URL of the proxy server. Pattern: "http://<server-ip>:<port>".
	URL string `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	// Username
	//
	// Username for the proxy server.
	Username string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	// Password
	//
	// Password for the proxy server.
	Password      string `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyInfo) Reset() {
	*x = ProxyInfo{}
	mi := &file_lightbits_api_duros_v2_proxy_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyInfo) ProtoMessage() {}

func (x *ProxyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lightbits_api_duros_v2_proxy_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyInfo.ProtoReflect.Descriptor instead.
func (*ProxyInfo) Descriptor() ([]byte, []int) {
	return file_lightbits_api_duros_v2_proxy_info_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyInfo) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *ProxyInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProxyInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_lightbits_api_duros_v2_proxy_info_proto protoreflect.FileDescriptor

const file_lightbits_api_duros_v2_proxy_info_proto_rawDesc = "" +
	"\n" +
	"'lightbits/api/duros/v2/proxy_info.proto\x12\x16lightbits.api.duros.v2\"U\n" +
	"\tProxyInfo\x12\x10\n" +
	"\x03URL\x18\x01 \x01(\tR\x03URL\x12\x1a\n" +
	"\bUsername\x18\x02 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPasswordB\rZ\vduros/v2;v2b\x06proto3"

var (
	file_lightbits_api_duros_v2_proxy_info_proto_rawDescOnce sync.Once
	file_lightbits_api_duros_v2_proxy_info_proto_rawDescData []byte
)

func file_lightbits_api_duros_v2_proxy_info_proto_rawDescGZIP() []byte {
	file_lightbits_api_duros_v2_proxy_info_proto_rawDescOnce.Do(func() {
		file_lightbits_api_duros_v2_proxy_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lightbits_api_duros_v2_proxy_info_proto_rawDesc), len(file_lightbits_api_duros_v2_proxy_info_proto_rawDesc)))
	})
	return file_lightbits_api_duros_v2_proxy_info_proto_rawDescData
}

var file_lightbits_api_duros_v2_proxy_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_lightbits_api_duros_v2_proxy_info_proto_goTypes = []any{
	(*ProxyInfo)(nil), // 0: lightbits.api.duros.v2.ProxyInfo
}
var file_lightbits_api_duros_v2_proxy_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lightbits_api_duros_v2_proxy_info_proto_init() }
func file_lightbits_api_duros_v2_proxy_info_proto_init() {
	if File_lightbits_api_duros_v2_proxy_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lightbits_api_duros_v2_proxy_info_proto_rawDesc), len(file_lightbits_api_duros_v2_proxy_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lightbits_api_duros_v2_proxy_info_proto_goTypes,
		DependencyIndexes: file_lightbits_api_duros_v2_proxy_info_proto_depIdxs,
		MessageInfos:      file_lightbits_api_duros_v2_proxy_info_proto_msgTypes,
	}.Build()
	File_lightbits_api_duros_v2_proxy_info_proto = out.File
	file_lightbits_api_duros_v2_proxy_info_proto_goTypes = nil
	file_lightbits_api_duros_v2_proxy_info_proto_depIdxs = nil
}
