// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grpc/gateway/protoc_gen_swagger/options/annotations.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*Swagger)(nil),
		Field:         1042,
		Name:          "grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger",
		Tag:           "bytes,1042,opt,name=openapiv2_swagger",
		Filename:      "grpc/gateway/protoc_gen_swagger/options/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Operation)(nil),
		Field:         1042,
		Name:          "grpc.gateway.protoc_gen_swagger.options.openapiv2_operation",
		Tag:           "bytes,1042,opt,name=openapiv2_operation",
		Filename:      "grpc/gateway/protoc_gen_swagger/options/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Schema)(nil),
		Field:         1042,
		Name:          "grpc.gateway.protoc_gen_swagger.options.openapiv2_schema",
		Tag:           "bytes,1042,opt,name=openapiv2_schema",
		Filename:      "grpc/gateway/protoc_gen_swagger/options/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Tag)(nil),
		Field:         1042,
		Name:          "grpc.gateway.protoc_gen_swagger.options.openapiv2_tag",
		Tag:           "bytes,1042,opt,name=openapiv2_tag",
		Filename:      "grpc/gateway/protoc_gen_swagger/options/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*JSONSchema)(nil),
		Field:         1042,
		Name:          "grpc.gateway.protoc_gen_swagger.options.openapiv2_field",
		Tag:           "bytes,1042,opt,name=openapiv2_field",
		Filename:      "grpc/gateway/protoc_gen_swagger/options/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// ID assigned by protobuf-global-extension-registry@google.com for grpc-gateway project.
	//
	// All IDs are the same, as assigned. It is okay that they are the same, as they extend
	// different descriptor messages.
	//
	// optional grpc.gateway.protoc_gen_swagger.options.Swagger openapiv2_swagger = 1042;
	E_Openapiv2Swagger = &file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// ID assigned by protobuf-global-extension-registry@google.com for grpc-gateway project.
	//
	// All IDs are the same, as assigned. It is okay that they are the same, as they extend
	// different descriptor messages.
	//
	// optional grpc.gateway.protoc_gen_swagger.options.Operation openapiv2_operation = 1042;
	E_Openapiv2Operation = &file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// ID assigned by protobuf-global-extension-registry@google.com for grpc-gateway project.
	//
	// All IDs are the same, as assigned. It is okay that they are the same, as they extend
	// different descriptor messages.
	//
	// optional grpc.gateway.protoc_gen_swagger.options.Schema openapiv2_schema = 1042;
	E_Openapiv2Schema = &file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// ID assigned by protobuf-global-extension-registry@google.com for grpc-gateway project.
	//
	// All IDs are the same, as assigned. It is okay that they are the same, as they extend
	// different descriptor messages.
	//
	// optional grpc.gateway.protoc_gen_swagger.options.Tag openapiv2_tag = 1042;
	E_Openapiv2Tag = &file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_extTypes[3]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// ID assigned by protobuf-global-extension-registry@google.com for grpc-gateway project.
	//
	// All IDs are the same, as assigned. It is okay that they are the same, as they extend
	// different descriptor messages.
	//
	// optional grpc.gateway.protoc_gen_swagger.options.JSONSchema openapiv2_field = 1042;
	E_Openapiv2Field = &file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_extTypes[4]
)

var File_grpc_gateway_protoc_gen_swagger_options_annotations_proto protoreflect.FileDescriptor

const file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_rawDesc = "" +
	"\n" +
	"9grpc/gateway/protoc_gen_swagger/options/annotations.proto\x12'grpc.gateway.protoc_gen_swagger.options\x1a google/protobuf/descriptor.proto\x1a7grpc/gateway/protoc_gen_swagger/options/openapiv2.proto:|\n" +
	"\x11openapiv2_swagger\x12\x1c.google.protobuf.FileOptions\x18\x92\b \x01(\v20.grpc.gateway.protoc_gen_swagger.options.SwaggerR\x10openapiv2Swagger:\x84\x01\n" +
	"\x13openapiv2_operation\x12\x1e.google.protobuf.MethodOptions\x18\x92\b \x01(\v22.grpc.gateway.protoc_gen_swagger.options.OperationR\x12openapiv2Operation:|\n" +
	"\x10openapiv2_schema\x12\x1f.google.protobuf.MessageOptions\x18\x92\b \x01(\v2/.grpc.gateway.protoc_gen_swagger.options.SchemaR\x0fopenapiv2Schema:s\n" +
	"\ropenapiv2_tag\x12\x1f.google.protobuf.ServiceOptions\x18\x92\b \x01(\v2,.grpc.gateway.protoc_gen_swagger.options.TagR\fopenapiv2Tag:|\n" +
	"\x0fopenapiv2_field\x12\x1d.google.protobuf.FieldOptions\x18\x92\b \x01(\v23.grpc.gateway.protoc_gen_swagger.options.JSONSchemaR\x0eopenapiv2FieldBCZAgithub.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/optionsb\x06proto3"

var file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_goTypes = []any{
	(*descriptorpb.FileOptions)(nil),    // 0: google.protobuf.FileOptions
	(*descriptorpb.MethodOptions)(nil),  // 1: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
	(*descriptorpb.ServiceOptions)(nil), // 3: google.protobuf.ServiceOptions
	(*descriptorpb.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
	(*Swagger)(nil),                     // 5: grpc.gateway.protoc_gen_swagger.options.Swagger
	(*Operation)(nil),                   // 6: grpc.gateway.protoc_gen_swagger.options.Operation
	(*Schema)(nil),                      // 7: grpc.gateway.protoc_gen_swagger.options.Schema
	(*Tag)(nil),                         // 8: grpc.gateway.protoc_gen_swagger.options.Tag
	(*JSONSchema)(nil),                  // 9: grpc.gateway.protoc_gen_swagger.options.JSONSchema
}
var file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_depIdxs = []int32{
	0,  // 0: grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger:extendee -> google.protobuf.FileOptions
	1,  // 1: grpc.gateway.protoc_gen_swagger.options.openapiv2_operation:extendee -> google.protobuf.MethodOptions
	2,  // 2: grpc.gateway.protoc_gen_swagger.options.openapiv2_schema:extendee -> google.protobuf.MessageOptions
	3,  // 3: grpc.gateway.protoc_gen_swagger.options.openapiv2_tag:extendee -> google.protobuf.ServiceOptions
	4,  // 4: grpc.gateway.protoc_gen_swagger.options.openapiv2_field:extendee -> google.protobuf.FieldOptions
	5,  // 5: grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger:type_name -> grpc.gateway.protoc_gen_swagger.options.Swagger
	6,  // 6: grpc.gateway.protoc_gen_swagger.options.openapiv2_operation:type_name -> grpc.gateway.protoc_gen_swagger.options.Operation
	7,  // 7: grpc.gateway.protoc_gen_swagger.options.openapiv2_schema:type_name -> grpc.gateway.protoc_gen_swagger.options.Schema
	8,  // 8: grpc.gateway.protoc_gen_swagger.options.openapiv2_tag:type_name -> grpc.gateway.protoc_gen_swagger.options.Tag
	9,  // 9: grpc.gateway.protoc_gen_swagger.options.openapiv2_field:type_name -> grpc.gateway.protoc_gen_swagger.options.JSONSchema
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	5,  // [5:10] is the sub-list for extension type_name
	0,  // [0:5] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_init() }
func file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_init() {
	if File_grpc_gateway_protoc_gen_swagger_options_annotations_proto != nil {
		return
	}
	file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_rawDesc), len(file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_goTypes,
		DependencyIndexes: file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_depIdxs,
		ExtensionInfos:    file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_extTypes,
	}.Build()
	File_grpc_gateway_protoc_gen_swagger_options_annotations_proto = out.File
	file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_goTypes = nil
	file_grpc_gateway_protoc_gen_swagger_options_annotations_proto_depIdxs = nil
}
