// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: grpc/gateway/protoc_gen_swagger/options/openapiv2.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Swagger_SwaggerScheme int32

const (
	Swagger_UNKNOWN Swagger_SwaggerScheme = 0
	Swagger_HTTP    Swagger_SwaggerScheme = 1
	Swagger_HTTPS   Swagger_SwaggerScheme = 2
	Swagger_WS      Swagger_SwaggerScheme = 3
	Swagger_WSS     Swagger_SwaggerScheme = 4
)

// Enum value maps for Swagger_SwaggerScheme.
var (
	Swagger_SwaggerScheme_name = map[int32]string{
		0: "UNKNOWN",
		1: "HTTP",
		2: "HTTPS",
		3: "WS",
		4: "WSS",
	}
	Swagger_SwaggerScheme_value = map[string]int32{
		"UNKNOWN": 0,
		"HTTP":    1,
		"HTTPS":   2,
		"WS":      3,
		"WSS":     4,
	}
)

func (x Swagger_SwaggerScheme) Enum() *Swagger_SwaggerScheme {
	p := new(Swagger_SwaggerScheme)
	*p = x
	return p
}

func (x Swagger_SwaggerScheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Swagger_SwaggerScheme) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_enumTypes[0].Descriptor()
}

func (Swagger_SwaggerScheme) Type() protoreflect.EnumType {
	return &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_enumTypes[0]
}

func (x Swagger_SwaggerScheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Swagger_SwaggerScheme.Descriptor instead.
func (Swagger_SwaggerScheme) EnumDescriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{0, 0}
}

type JSONSchema_JSONSchemaSimpleTypes int32

const (
	JSONSchema_UNKNOWN JSONSchema_JSONSchemaSimpleTypes = 0
	JSONSchema_ARRAY   JSONSchema_JSONSchemaSimpleTypes = 1
	JSONSchema_BOOLEAN JSONSchema_JSONSchemaSimpleTypes = 2
	JSONSchema_INTEGER JSONSchema_JSONSchemaSimpleTypes = 3
	JSONSchema_NULL    JSONSchema_JSONSchemaSimpleTypes = 4
	JSONSchema_NUMBER  JSONSchema_JSONSchemaSimpleTypes = 5
	JSONSchema_OBJECT  JSONSchema_JSONSchemaSimpleTypes = 6
	JSONSchema_STRING  JSONSchema_JSONSchemaSimpleTypes = 7
)

// Enum value maps for JSONSchema_JSONSchemaSimpleTypes.
var (
	JSONSchema_JSONSchemaSimpleTypes_name = map[int32]string{
		0: "UNKNOWN",
		1: "ARRAY",
		2: "BOOLEAN",
		3: "INTEGER",
		4: "NULL",
		5: "NUMBER",
		6: "OBJECT",
		7: "STRING",
	}
	JSONSchema_JSONSchemaSimpleTypes_value = map[string]int32{
		"UNKNOWN": 0,
		"ARRAY":   1,
		"BOOLEAN": 2,
		"INTEGER": 3,
		"NULL":    4,
		"NUMBER":  5,
		"OBJECT":  6,
		"STRING":  7,
	}
)

func (x JSONSchema_JSONSchemaSimpleTypes) Enum() *JSONSchema_JSONSchemaSimpleTypes {
	p := new(JSONSchema_JSONSchemaSimpleTypes)
	*p = x
	return p
}

func (x JSONSchema_JSONSchemaSimpleTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JSONSchema_JSONSchemaSimpleTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_enumTypes[1].Descriptor()
}

func (JSONSchema_JSONSchemaSimpleTypes) Type() protoreflect.EnumType {
	return &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_enumTypes[1]
}

func (x JSONSchema_JSONSchemaSimpleTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JSONSchema_JSONSchemaSimpleTypes.Descriptor instead.
func (JSONSchema_JSONSchemaSimpleTypes) EnumDescriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{9, 0}
}

// The type of the security scheme. Valid values are "basic",
// "apiKey" or "oauth2".
type SecurityScheme_Type int32

const (
	SecurityScheme_TYPE_INVALID SecurityScheme_Type = 0
	SecurityScheme_TYPE_BASIC   SecurityScheme_Type = 1
	SecurityScheme_TYPE_API_KEY SecurityScheme_Type = 2
	SecurityScheme_TYPE_OAUTH2  SecurityScheme_Type = 3
)

// Enum value maps for SecurityScheme_Type.
var (
	SecurityScheme_Type_name = map[int32]string{
		0: "TYPE_INVALID",
		1: "TYPE_BASIC",
		2: "TYPE_API_KEY",
		3: "TYPE_OAUTH2",
	}
	SecurityScheme_Type_value = map[string]int32{
		"TYPE_INVALID": 0,
		"TYPE_BASIC":   1,
		"TYPE_API_KEY": 2,
		"TYPE_OAUTH2":  3,
	}
)

func (x SecurityScheme_Type) Enum() *SecurityScheme_Type {
	p := new(SecurityScheme_Type)
	*p = x
	return p
}

func (x SecurityScheme_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityScheme_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_enumTypes[2].Descriptor()
}

func (SecurityScheme_Type) Type() protoreflect.EnumType {
	return &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_enumTypes[2]
}

func (x SecurityScheme_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecurityScheme_Type.Descriptor instead.
func (SecurityScheme_Type) EnumDescriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{12, 0}
}

// The location of the API key. Valid values are "query" or "header".
type SecurityScheme_In int32

const (
	SecurityScheme_IN_INVALID SecurityScheme_In = 0
	SecurityScheme_IN_QUERY   SecurityScheme_In = 1
	SecurityScheme_IN_HEADER  SecurityScheme_In = 2
)

// Enum value maps for SecurityScheme_In.
var (
	SecurityScheme_In_name = map[int32]string{
		0: "IN_INVALID",
		1: "IN_QUERY",
		2: "IN_HEADER",
	}
	SecurityScheme_In_value = map[string]int32{
		"IN_INVALID": 0,
		"IN_QUERY":   1,
		"IN_HEADER":  2,
	}
)

func (x SecurityScheme_In) Enum() *SecurityScheme_In {
	p := new(SecurityScheme_In)
	*p = x
	return p
}

func (x SecurityScheme_In) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityScheme_In) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_enumTypes[3].Descriptor()
}

func (SecurityScheme_In) Type() protoreflect.EnumType {
	return &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_enumTypes[3]
}

func (x SecurityScheme_In) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecurityScheme_In.Descriptor instead.
func (SecurityScheme_In) EnumDescriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{12, 1}
}

// The flow used by the OAuth2 security scheme. Valid values are
// "implicit", "password", "application" or "accessCode".
type SecurityScheme_Flow int32

const (
	SecurityScheme_FLOW_INVALID     SecurityScheme_Flow = 0
	SecurityScheme_FLOW_IMPLICIT    SecurityScheme_Flow = 1
	SecurityScheme_FLOW_PASSWORD    SecurityScheme_Flow = 2
	SecurityScheme_FLOW_APPLICATION SecurityScheme_Flow = 3
	SecurityScheme_FLOW_ACCESS_CODE SecurityScheme_Flow = 4
)

// Enum value maps for SecurityScheme_Flow.
var (
	SecurityScheme_Flow_name = map[int32]string{
		0: "FLOW_INVALID",
		1: "FLOW_IMPLICIT",
		2: "FLOW_PASSWORD",
		3: "FLOW_APPLICATION",
		4: "FLOW_ACCESS_CODE",
	}
	SecurityScheme_Flow_value = map[string]int32{
		"FLOW_INVALID":     0,
		"FLOW_IMPLICIT":    1,
		"FLOW_PASSWORD":    2,
		"FLOW_APPLICATION": 3,
		"FLOW_ACCESS_CODE": 4,
	}
)

func (x SecurityScheme_Flow) Enum() *SecurityScheme_Flow {
	p := new(SecurityScheme_Flow)
	*p = x
	return p
}

func (x SecurityScheme_Flow) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityScheme_Flow) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_enumTypes[4].Descriptor()
}

func (SecurityScheme_Flow) Type() protoreflect.EnumType {
	return &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_enumTypes[4]
}

func (x SecurityScheme_Flow) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecurityScheme_Flow.Descriptor instead.
func (SecurityScheme_Flow) EnumDescriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{12, 2}
}

// `Swagger` is a representation of OpenAPI v2 specification's Swagger object.
//
// See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#swaggerObject
//
// Example:
//
//	option (grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger) = {
//	  info: {
//	    title: "Echo API";
//	    version: "1.0";
//	    description: ";
//	    contact: {
//	      name: "gRPC-Gateway project";
//	      url: "https://github.com/grpc-ecosystem/grpc-gateway";
//	      email: "none@example.com";
//	    };
//	    license: {
//	      name: "BSD 3-Clause License";
//	      url: "https://github.com/grpc-ecosystem/grpc-gateway/blob/master/LICENSE.txt";
//	    };
//	  };
//	  schemes: HTTPS;
//	  consumes: "application/json";
//	  produces: "application/json";
//	};
type Swagger struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the Swagger Specification version being used. It can be
	// used by the Swagger UI and other clients to interpret the API listing. The
	// value MUST be "2.0".
	Swagger string `protobuf:"bytes,1,opt,name=swagger,proto3" json:"swagger,omitempty"`
	// Provides metadata about the API. The metadata can be used by the
	// clients if needed.
	Info *Info `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// The host (name or ip) serving the API. This MUST be the host only and does
	// not include the scheme nor sub-paths. It MAY include a port. If the host is
	// not included, the host serving the documentation is to be used (including
	// the port). The host does not support path templating.
	Host string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	// The base path on which the API is served, which is relative to the host. If
	// it is not included, the API is served directly under the host. The value
	// MUST start with a leading slash (/). The basePath does not support path
	// templating.
	// Note that using `base_path` does not change the endpoint paths that are
	// generated in the resulting Swagger file. If you wish to use `base_path`
	// with relatively generated Swagger paths, the `base_path` prefix must be
	// manually removed from your `google.api.http` paths and your code changed to
	// serve the API from the `base_path`.
	BasePath string `protobuf:"bytes,4,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	// The transfer protocol of the API. Values MUST be from the list: "http",
	// "https", "ws", "wss". If the schemes is not included, the default scheme to
	// be used is the one used to access the Swagger definition itself.
	Schemes []Swagger_SwaggerScheme `protobuf:"varint,5,rep,packed,name=schemes,proto3,enum=grpc.gateway.protoc_gen_swagger.options.Swagger_SwaggerScheme" json:"schemes,omitempty"`
	// A list of MIME types the APIs can consume. This is global to all APIs but
	// can be overridden on specific API calls. Value MUST be as described under
	// Mime Types.
	Consumes []string `protobuf:"bytes,6,rep,name=consumes,proto3" json:"consumes,omitempty"`
	// A list of MIME types the APIs can produce. This is global to all APIs but
	// can be overridden on specific API calls. Value MUST be as described under
	// Mime Types.
	Produces []string `protobuf:"bytes,7,rep,name=produces,proto3" json:"produces,omitempty"`
	// An object to hold responses that can be used across operations. This
	// property does not define global responses for all operations.
	Responses map[string]*Response `protobuf:"bytes,10,rep,name=responses,proto3" json:"responses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Security scheme definitions that can be used across the specification.
	SecurityDefinitions *SecurityDefinitions `protobuf:"bytes,11,opt,name=security_definitions,json=securityDefinitions,proto3" json:"security_definitions,omitempty"`
	// A declaration of which security schemes are applied for the API as a whole.
	// The list of values describes alternative security schemes that can be used
	// (that is, there is a logical OR between the security requirements).
	// Individual operations can override this definition.
	Security []*SecurityRequirement `protobuf:"bytes,12,rep,name=security,proto3" json:"security,omitempty"`
	// Additional external documentation.
	ExternalDocs  *ExternalDocumentation     `protobuf:"bytes,14,opt,name=external_docs,json=externalDocs,proto3" json:"external_docs,omitempty"`
	Extensions    map[string]*structpb.Value `protobuf:"bytes,15,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Swagger) Reset() {
	*x = Swagger{}
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Swagger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Swagger) ProtoMessage() {}

func (x *Swagger) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Swagger.ProtoReflect.Descriptor instead.
func (*Swagger) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{0}
}

func (x *Swagger) GetSwagger() string {
	if x != nil {
		return x.Swagger
	}
	return ""
}

func (x *Swagger) GetInfo() *Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Swagger) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Swagger) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

func (x *Swagger) GetSchemes() []Swagger_SwaggerScheme {
	if x != nil {
		return x.Schemes
	}
	return nil
}

func (x *Swagger) GetConsumes() []string {
	if x != nil {
		return x.Consumes
	}
	return nil
}

func (x *Swagger) GetProduces() []string {
	if x != nil {
		return x.Produces
	}
	return nil
}

func (x *Swagger) GetResponses() map[string]*Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *Swagger) GetSecurityDefinitions() *SecurityDefinitions {
	if x != nil {
		return x.SecurityDefinitions
	}
	return nil
}

func (x *Swagger) GetSecurity() []*SecurityRequirement {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *Swagger) GetExternalDocs() *ExternalDocumentation {
	if x != nil {
		return x.ExternalDocs
	}
	return nil
}

func (x *Swagger) GetExtensions() map[string]*structpb.Value {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// `Operation` is a representation of OpenAPI v2 specification's Operation object.
//
// See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#operationObject
//
// Example:
//
//	service EchoService {
//	  rpc Echo(SimpleMessage) returns (SimpleMessage) {
//	    option (google.api.http) = {
//	      get: "/v1/example/echo/{id}"
//	    };
//
//	    option (grpc.gateway.protoc_gen_swagger.options.openapiv2_operation) = {
//	      summary: "Get a message.";
//	      operation_id: "getMessage";
//	      tags: "echo";
//	      responses: {
//	        key: "200"
//	          value: {
//	          description: "OK";
//	        }
//	      }
//	    };
//	  }
//	}
type Operation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of tags for API documentation control. Tags can be used for logical
	// grouping of operations by resources or any other qualifier.
	Tags []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	// A short summary of what the operation does. For maximum readability in the
	// swagger-ui, this field SHOULD be less than 120 characters.
	Summary string `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	// A verbose explanation of the operation behavior. GFM syntax can be used for
	// rich text representation.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Additional external documentation for this operation.
	ExternalDocs *ExternalDocumentation `protobuf:"bytes,4,opt,name=external_docs,json=externalDocs,proto3" json:"external_docs,omitempty"`
	// Unique string used to identify the operation. The id MUST be unique among
	// all operations described in the API. Tools and libraries MAY use the
	// operationId to uniquely identify an operation, therefore, it is recommended
	// to follow common programming naming conventions.
	OperationId string `protobuf:"bytes,5,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// A list of MIME types the operation can consume. This overrides the consumes
	// definition at the Swagger Object. An empty value MAY be used to clear the
	// global definition. Value MUST be as described under Mime Types.
	Consumes []string `protobuf:"bytes,6,rep,name=consumes,proto3" json:"consumes,omitempty"`
	// A list of MIME types the operation can produce. This overrides the produces
	// definition at the Swagger Object. An empty value MAY be used to clear the
	// global definition. Value MUST be as described under Mime Types.
	Produces []string `protobuf:"bytes,7,rep,name=produces,proto3" json:"produces,omitempty"`
	// The list of possible responses as they are returned from executing this
	// operation.
	Responses map[string]*Response `protobuf:"bytes,9,rep,name=responses,proto3" json:"responses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The transfer protocol for the operation. Values MUST be from the list:
	// "http", "https", "ws", "wss". The value overrides the Swagger Object
	// schemes definition.
	Schemes []string `protobuf:"bytes,10,rep,name=schemes,proto3" json:"schemes,omitempty"`
	// Declares this operation to be deprecated. Usage of the declared operation
	// should be refrained. Default value is false.
	Deprecated bool `protobuf:"varint,11,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	// A declaration of which security schemes are applied for this operation. The
	// list of values describes alternative security schemes that can be used
	// (that is, there is a logical OR between the security requirements). This
	// definition overrides any declared top-level security. To remove a top-level
	// security declaration, an empty array can be used.
	Security      []*SecurityRequirement     `protobuf:"bytes,12,rep,name=security,proto3" json:"security,omitempty"`
	Extensions    map[string]*structpb.Value `protobuf:"bytes,13,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{1}
}

func (x *Operation) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Operation) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Operation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Operation) GetExternalDocs() *ExternalDocumentation {
	if x != nil {
		return x.ExternalDocs
	}
	return nil
}

func (x *Operation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *Operation) GetConsumes() []string {
	if x != nil {
		return x.Consumes
	}
	return nil
}

func (x *Operation) GetProduces() []string {
	if x != nil {
		return x.Produces
	}
	return nil
}

func (x *Operation) GetResponses() map[string]*Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *Operation) GetSchemes() []string {
	if x != nil {
		return x.Schemes
	}
	return nil
}

func (x *Operation) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *Operation) GetSecurity() []*SecurityRequirement {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *Operation) GetExtensions() map[string]*structpb.Value {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// `Header` is a representation of OpenAPI v2 specification's Header object.
//
// See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#headerObject
type Header struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// `Description` is a short description of the header.
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// The type of the object. The value MUST be one of "string", "number", "integer", or "boolean". The "array" type is not supported.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// `Format` The extending format for the previously mentioned type.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// `Default` Declares the value of the header that the server will use if none is provided.
	// See: https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-6.2.
	// Unlike JSON Schema this value MUST conform to the defined type for the header.
	Default string `protobuf:"bytes,6,opt,name=default,proto3" json:"default,omitempty"`
	// 'Pattern' See https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.2.3.
	Pattern       string `protobuf:"bytes,13,opt,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{2}
}

func (x *Header) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Header) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Header) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Header) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *Header) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

// `Response` is a representation of OpenAPI v2 specification's Response object.
//
// See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#responseObject
type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// `Description` is a short description of the response.
	// GFM syntax can be used for rich text representation.
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// `Schema` optionally defines the structure of the response.
	// If `Schema` is not provided, it means there is no content to the response.
	Schema *Schema `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	// `Headers` A list of headers that are sent with the response.
	// `Header` name is expected to be a string in the canonical format of the MIME header key
	// See: https://golang.org/pkg/net/textproto/#CanonicalMIMEHeaderKey
	Headers map[string]*Header `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// `Examples` gives per-mimetype response examples.
	// See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#example-object
	Examples      map[string]string          `protobuf:"bytes,4,rep,name=examples,proto3" json:"examples,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Extensions    map[string]*structpb.Value `protobuf:"bytes,5,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Response) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Response) GetHeaders() map[string]*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Response) GetExamples() map[string]string {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *Response) GetExtensions() map[string]*structpb.Value {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// `Info` is a representation of OpenAPI v2 specification's Info object.
//
// See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#infoObject
//
// Example:
//
//	option (grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger) = {
//	  info: {
//	    title: "Echo API";
//	    version: "1.0";
//	    description: ";
//	    contact: {
//	      name: "gRPC-Gateway project";
//	      url: "https://github.com/grpc-ecosystem/grpc-gateway";
//	      email: "none@example.com";
//	    };
//	    license: {
//	      name: "BSD 3-Clause License";
//	      url: "https://github.com/grpc-ecosystem/grpc-gateway/blob/master/LICENSE.txt";
//	    };
//	  };
//	  ...
//	};
type Info struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The title of the application.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// A short description of the application. GFM syntax can be used for rich
	// text representation.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// The Terms of Service for the API.
	TermsOfService string `protobuf:"bytes,3,opt,name=terms_of_service,json=termsOfService,proto3" json:"terms_of_service,omitempty"`
	// The contact information for the exposed API.
	Contact *Contact `protobuf:"bytes,4,opt,name=contact,proto3" json:"contact,omitempty"`
	// The license information for the exposed API.
	License *License `protobuf:"bytes,5,opt,name=license,proto3" json:"license,omitempty"`
	// Provides the version of the application API (not to be confused
	// with the specification version).
	Version       string                     `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Extensions    map[string]*structpb.Value `protobuf:"bytes,7,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{4}
}

func (x *Info) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Info) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Info) GetTermsOfService() string {
	if x != nil {
		return x.TermsOfService
	}
	return ""
}

func (x *Info) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *Info) GetLicense() *License {
	if x != nil {
		return x.License
	}
	return nil
}

func (x *Info) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Info) GetExtensions() map[string]*structpb.Value {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// `Contact` is a representation of OpenAPI v2 specification's Contact object.
//
// See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#contactObject
//
// Example:
//
//	option (grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger) = {
//	  info: {
//	    ...
//	    contact: {
//	      name: "gRPC-Gateway project";
//	      url: "https://github.com/grpc-ecosystem/grpc-gateway";
//	      email: "none@example.com";
//	    };
//	    ...
//	  };
//	  ...
//	};
type Contact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifying name of the contact person/organization.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The URL pointing to the contact information. MUST be in the format of a
	// URL.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// The email address of the contact person/organization. MUST be in the format
	// of an email address.
	Email         string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{5}
}

func (x *Contact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contact) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// `License` is a representation of OpenAPI v2 specification's License object.
//
// See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#licenseObject
//
// Example:
//
//	option (grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger) = {
//	  info: {
//	    ...
//	    license: {
//	      name: "BSD 3-Clause License";
//	      url: "https://github.com/grpc-ecosystem/grpc-gateway/blob/master/LICENSE.txt";
//	    };
//	    ...
//	  };
//	  ...
//	};
type License struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The license name used for the API.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A URL to the license used for the API. MUST be in the format of a URL.
	Url           string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *License) Reset() {
	*x = License{}
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *License) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*License) ProtoMessage() {}

func (x *License) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use License.ProtoReflect.Descriptor instead.
func (*License) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{6}
}

func (x *License) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *License) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// `ExternalDocumentation` is a representation of OpenAPI v2 specification's
// ExternalDocumentation object.
//
// See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#externalDocumentationObject
//
// Example:
//
//	option (grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger) = {
//	  ...
//	  external_docs: {
//	    description: "More about gRPC-Gateway";
//	    url: "https://github.com/grpc-ecosystem/grpc-gateway";
//	  }
//	  ...
//	};
type ExternalDocumentation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A short description of the target documentation. GFM syntax can be used for
	// rich text representation.
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// The URL for the target documentation. Value MUST be in the format
	// of a URL.
	Url           string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalDocumentation) Reset() {
	*x = ExternalDocumentation{}
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalDocumentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalDocumentation) ProtoMessage() {}

func (x *ExternalDocumentation) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalDocumentation.ProtoReflect.Descriptor instead.
func (*ExternalDocumentation) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{7}
}

func (x *ExternalDocumentation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExternalDocumentation) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// `Schema` is a representation of OpenAPI v2 specification's Schema object.
//
// See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#schemaObject
type Schema struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	JsonSchema *JSONSchema            `protobuf:"bytes,1,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	// Adds support for polymorphism. The discriminator is the schema property
	// name that is used to differentiate between other schema that inherit this
	// schema. The property name used MUST be defined at this schema and it MUST
	// be in the required property list. When used, the value MUST be the name of
	// this schema or any schema that inherits it.
	Discriminator string `protobuf:"bytes,2,opt,name=discriminator,proto3" json:"discriminator,omitempty"`
	// Relevant only for Schema "properties" definitions. Declares the property as
	// "read only". This means that it MAY be sent as part of a response but MUST
	// NOT be sent as part of the request. Properties marked as readOnly being
	// true SHOULD NOT be in the required list of the defined schema. Default
	// value is false.
	ReadOnly bool `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// Additional external documentation for this schema.
	ExternalDocs *ExternalDocumentation `protobuf:"bytes,5,opt,name=external_docs,json=externalDocs,proto3" json:"external_docs,omitempty"`
	// A free-form property to include an example of an instance for this schema.
	// Deprecated, please use example_string instead.
	//
	// Deprecated: Marked as deprecated in grpc/gateway/protoc_gen_swagger/options/openapiv2.proto.
	Example *anypb.Any `protobuf:"bytes,6,opt,name=example,proto3" json:"example,omitempty"`
	// A free-form property to include a JSON example of this field. This is copied
	// verbatim to the output swagger.json. Quotes must be escaped.
	ExampleString string `protobuf:"bytes,7,opt,name=example_string,json=exampleString,proto3" json:"example_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{8}
}

func (x *Schema) GetJsonSchema() *JSONSchema {
	if x != nil {
		return x.JsonSchema
	}
	return nil
}

func (x *Schema) GetDiscriminator() string {
	if x != nil {
		return x.Discriminator
	}
	return ""
}

func (x *Schema) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *Schema) GetExternalDocs() *ExternalDocumentation {
	if x != nil {
		return x.ExternalDocs
	}
	return nil
}

// Deprecated: Marked as deprecated in grpc/gateway/protoc_gen_swagger/options/openapiv2.proto.
func (x *Schema) GetExample() *anypb.Any {
	if x != nil {
		return x.Example
	}
	return nil
}

func (x *Schema) GetExampleString() string {
	if x != nil {
		return x.ExampleString
	}
	return ""
}

// `JSONSchema` represents properties from JSON Schema taken, and as used, in
// the OpenAPI v2 spec.
//
// This includes changes made by OpenAPI v2.
//
// See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#schemaObject
//
// See also: https://cswr.github.io/JsonSchema/spec/basic_types/,
// https://github.com/json-schema-org/json-schema-spec/blob/master/schema.json
//
// Example:
//
//	message SimpleMessage {
//	  option (grpc.gateway.protoc_gen_swagger.options.openapiv2_schema) = {
//	    json_schema: {
//	      title: "SimpleMessage"
//	      description: "A simple message."
//	      required: ["id"]
//	    }
//	  };
//
//	  // Id represents the message identifier.
//	  string id = 1; [
//	      (grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
//	        {description: "The unique identifier of the simple message."
//	      }];
//	}
type JSONSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ref is used to define an external reference to include in the message.
	// This could be a fully qualified proto message reference, and that type must
	// be imported into the protofile. If no message is identified, the Ref will
	// be used verbatim in the output.
	// For example:
	//
	//	`ref: ".google.protobuf.Timestamp"`.
	Ref string `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	// The title of the schema.
	Title string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	// A short description of the schema.
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Default     string `protobuf:"bytes,7,opt,name=default,proto3" json:"default,omitempty"`
	ReadOnly    bool   `protobuf:"varint,8,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// A free-form property to include a JSON example of this field. This is copied
	// verbatim to the output swagger.json. Quotes must be escaped.
	// This property is the same for 2.0 and 3.0.0 https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/3.0.0.md#schemaObject  https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#schemaObject
	Example    string  `protobuf:"bytes,9,opt,name=example,proto3" json:"example,omitempty"`
	MultipleOf float64 `protobuf:"fixed64,10,opt,name=multiple_of,json=multipleOf,proto3" json:"multiple_of,omitempty"`
	// Maximum represents an inclusive upper limit for a numeric instance. The
	// value of MUST be a number,
	Maximum          float64 `protobuf:"fixed64,11,opt,name=maximum,proto3" json:"maximum,omitempty"`
	ExclusiveMaximum bool    `protobuf:"varint,12,opt,name=exclusive_maximum,json=exclusiveMaximum,proto3" json:"exclusive_maximum,omitempty"`
	// minimum represents an inclusive lower limit for a numeric instance. The
	// value of MUST be a number,
	Minimum          float64  `protobuf:"fixed64,13,opt,name=minimum,proto3" json:"minimum,omitempty"`
	ExclusiveMinimum bool     `protobuf:"varint,14,opt,name=exclusive_minimum,json=exclusiveMinimum,proto3" json:"exclusive_minimum,omitempty"`
	MaxLength        uint64   `protobuf:"varint,15,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	MinLength        uint64   `protobuf:"varint,16,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"`
	Pattern          string   `protobuf:"bytes,17,opt,name=pattern,proto3" json:"pattern,omitempty"`
	MaxItems         uint64   `protobuf:"varint,20,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`
	MinItems         uint64   `protobuf:"varint,21,opt,name=min_items,json=minItems,proto3" json:"min_items,omitempty"`
	UniqueItems      bool     `protobuf:"varint,22,opt,name=unique_items,json=uniqueItems,proto3" json:"unique_items,omitempty"`
	MaxProperties    uint64   `protobuf:"varint,24,opt,name=max_properties,json=maxProperties,proto3" json:"max_properties,omitempty"`
	MinProperties    uint64   `protobuf:"varint,25,opt,name=min_properties,json=minProperties,proto3" json:"min_properties,omitempty"`
	Required         []string `protobuf:"bytes,26,rep,name=required,proto3" json:"required,omitempty"`
	// Items in 'array' must be unique.
	Array []string                           `protobuf:"bytes,34,rep,name=array,proto3" json:"array,omitempty"`
	Type  []JSONSchema_JSONSchemaSimpleTypes `protobuf:"varint,35,rep,packed,name=type,proto3,enum=grpc.gateway.protoc_gen_swagger.options.JSONSchema_JSONSchemaSimpleTypes" json:"type,omitempty"`
	// `Format`
	Format string `protobuf:"bytes,36,opt,name=format,proto3" json:"format,omitempty"`
	// Items in `enum` must be unique https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.5.1
	Enum          []string `protobuf:"bytes,46,rep,name=enum,proto3" json:"enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONSchema) Reset() {
	*x = JSONSchema{}
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONSchema) ProtoMessage() {}

func (x *JSONSchema) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONSchema.ProtoReflect.Descriptor instead.
func (*JSONSchema) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{9}
}

func (x *JSONSchema) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *JSONSchema) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JSONSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JSONSchema) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *JSONSchema) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *JSONSchema) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

func (x *JSONSchema) GetMultipleOf() float64 {
	if x != nil {
		return x.MultipleOf
	}
	return 0
}

func (x *JSONSchema) GetMaximum() float64 {
	if x != nil {
		return x.Maximum
	}
	return 0
}

func (x *JSONSchema) GetExclusiveMaximum() bool {
	if x != nil {
		return x.ExclusiveMaximum
	}
	return false
}

func (x *JSONSchema) GetMinimum() float64 {
	if x != nil {
		return x.Minimum
	}
	return 0
}

func (x *JSONSchema) GetExclusiveMinimum() bool {
	if x != nil {
		return x.ExclusiveMinimum
	}
	return false
}

func (x *JSONSchema) GetMaxLength() uint64 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *JSONSchema) GetMinLength() uint64 {
	if x != nil {
		return x.MinLength
	}
	return 0
}

func (x *JSONSchema) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *JSONSchema) GetMaxItems() uint64 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

func (x *JSONSchema) GetMinItems() uint64 {
	if x != nil {
		return x.MinItems
	}
	return 0
}

func (x *JSONSchema) GetUniqueItems() bool {
	if x != nil {
		return x.UniqueItems
	}
	return false
}

func (x *JSONSchema) GetMaxProperties() uint64 {
	if x != nil {
		return x.MaxProperties
	}
	return 0
}

func (x *JSONSchema) GetMinProperties() uint64 {
	if x != nil {
		return x.MinProperties
	}
	return 0
}

func (x *JSONSchema) GetRequired() []string {
	if x != nil {
		return x.Required
	}
	return nil
}

func (x *JSONSchema) GetArray() []string {
	if x != nil {
		return x.Array
	}
	return nil
}

func (x *JSONSchema) GetType() []JSONSchema_JSONSchemaSimpleTypes {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *JSONSchema) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *JSONSchema) GetEnum() []string {
	if x != nil {
		return x.Enum
	}
	return nil
}

// `Tag` is a representation of OpenAPI v2 specification's Tag object.
//
// See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#tagObject
type Tag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A short description for the tag. GFM syntax can be used for rich text
	// representation.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Additional external documentation for this tag.
	ExternalDocs  *ExternalDocumentation `protobuf:"bytes,3,opt,name=external_docs,json=externalDocs,proto3" json:"external_docs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{10}
}

func (x *Tag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tag) GetExternalDocs() *ExternalDocumentation {
	if x != nil {
		return x.ExternalDocs
	}
	return nil
}

// `SecurityDefinitions` is a representation of OpenAPI v2 specification's
// Security Definitions object.
//
// See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#securityDefinitionsObject
//
// A declaration of the security schemes available to be used in the
// specification. This does not enforce the security schemes on the operations
// and only serves to provide the relevant details for each scheme.
type SecurityDefinitions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A single security scheme definition, mapping a "name" to the scheme it
	// defines.
	Security      map[string]*SecurityScheme `protobuf:"bytes,1,rep,name=security,proto3" json:"security,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityDefinitions) Reset() {
	*x = SecurityDefinitions{}
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityDefinitions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityDefinitions) ProtoMessage() {}

func (x *SecurityDefinitions) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityDefinitions.ProtoReflect.Descriptor instead.
func (*SecurityDefinitions) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{11}
}

func (x *SecurityDefinitions) GetSecurity() map[string]*SecurityScheme {
	if x != nil {
		return x.Security
	}
	return nil
}

// `SecurityScheme` is a representation of OpenAPI v2 specification's
// Security Scheme object.
//
// See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#securitySchemeObject
//
// Allows the definition of a security scheme that can be used by the
// operations. Supported schemes are basic authentication, an API key (either as
// a header or as a query parameter) and OAuth2's common flows (implicit,
// password, application and access code).
type SecurityScheme struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the security scheme. Valid values are "basic",
	// "apiKey" or "oauth2".
	Type SecurityScheme_Type `protobuf:"varint,1,opt,name=type,proto3,enum=grpc.gateway.protoc_gen_swagger.options.SecurityScheme_Type" json:"type,omitempty"`
	// A short description for security scheme.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// The name of the header or query parameter to be used.
	// Valid for apiKey.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The location of the API key. Valid values are "query" or
	// "header".
	// Valid for apiKey.
	In SecurityScheme_In `protobuf:"varint,4,opt,name=in,proto3,enum=grpc.gateway.protoc_gen_swagger.options.SecurityScheme_In" json:"in,omitempty"`
	// The flow used by the OAuth2 security scheme. Valid values are
	// "implicit", "password", "application" or "accessCode".
	// Valid for oauth2.
	Flow SecurityScheme_Flow `protobuf:"varint,5,opt,name=flow,proto3,enum=grpc.gateway.protoc_gen_swagger.options.SecurityScheme_Flow" json:"flow,omitempty"`
	// The authorization URL to be used for this flow. This SHOULD be in
	// the form of a URL.
	// Valid for oauth2/implicit and oauth2/accessCode.
	AuthorizationUrl string `protobuf:"bytes,6,opt,name=authorization_url,json=authorizationUrl,proto3" json:"authorization_url,omitempty"`
	// The token URL to be used for this flow. This SHOULD be in the
	// form of a URL.
	// Valid for oauth2/password, oauth2/application and oauth2/accessCode.
	TokenUrl string `protobuf:"bytes,7,opt,name=token_url,json=tokenUrl,proto3" json:"token_url,omitempty"`
	// The available scopes for the OAuth2 security scheme.
	// Valid for oauth2.
	Scopes        *Scopes                    `protobuf:"bytes,8,opt,name=scopes,proto3" json:"scopes,omitempty"`
	Extensions    map[string]*structpb.Value `protobuf:"bytes,9,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityScheme) Reset() {
	*x = SecurityScheme{}
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityScheme) ProtoMessage() {}

func (x *SecurityScheme) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityScheme.ProtoReflect.Descriptor instead.
func (*SecurityScheme) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{12}
}

func (x *SecurityScheme) GetType() SecurityScheme_Type {
	if x != nil {
		return x.Type
	}
	return SecurityScheme_TYPE_INVALID
}

func (x *SecurityScheme) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SecurityScheme) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecurityScheme) GetIn() SecurityScheme_In {
	if x != nil {
		return x.In
	}
	return SecurityScheme_IN_INVALID
}

func (x *SecurityScheme) GetFlow() SecurityScheme_Flow {
	if x != nil {
		return x.Flow
	}
	return SecurityScheme_FLOW_INVALID
}

func (x *SecurityScheme) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

func (x *SecurityScheme) GetTokenUrl() string {
	if x != nil {
		return x.TokenUrl
	}
	return ""
}

func (x *SecurityScheme) GetScopes() *Scopes {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *SecurityScheme) GetExtensions() map[string]*structpb.Value {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// `SecurityRequirement` is a representation of OpenAPI v2 specification's
// Security Requirement object.
//
// See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#securityRequirementObject
//
// Lists the required security schemes to execute this operation. The object can
// have multiple security schemes declared in it which are all required (that
// is, there is a logical AND between the schemes).
//
// The name used for each property MUST correspond to a security scheme
// declared in the Security Definitions.
type SecurityRequirement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each name must correspond to a security scheme which is declared in
	// the Security Definitions. If the security scheme is of type "oauth2",
	// then the value is a list of scope names required for the execution.
	// For other security scheme types, the array MUST be empty.
	SecurityRequirement map[string]*SecurityRequirement_SecurityRequirementValue `protobuf:"bytes,1,rep,name=security_requirement,json=securityRequirement,proto3" json:"security_requirement,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SecurityRequirement) Reset() {
	*x = SecurityRequirement{}
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityRequirement) ProtoMessage() {}

func (x *SecurityRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityRequirement.ProtoReflect.Descriptor instead.
func (*SecurityRequirement) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{13}
}

func (x *SecurityRequirement) GetSecurityRequirement() map[string]*SecurityRequirement_SecurityRequirementValue {
	if x != nil {
		return x.SecurityRequirement
	}
	return nil
}

// `Scopes` is a representation of OpenAPI v2 specification's Scopes object.
//
// See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#scopesObject
//
// Lists the available scopes for an OAuth2 security scheme.
type Scopes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maps between a name of a scope to a short description of it (as the value
	// of the property).
	Scope         map[string]string `protobuf:"bytes,1,rep,name=scope,proto3" json:"scope,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scopes) Reset() {
	*x = Scopes{}
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scopes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scopes) ProtoMessage() {}

func (x *Scopes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scopes.ProtoReflect.Descriptor instead.
func (*Scopes) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{14}
}

func (x *Scopes) GetScope() map[string]string {
	if x != nil {
		return x.Scope
	}
	return nil
}

// If the security scheme is of type "oauth2", then the value is a list of
// scope names required for the execution. For other security scheme types,
// the array MUST be empty.
type SecurityRequirement_SecurityRequirementValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         []string               `protobuf:"bytes,1,rep,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityRequirement_SecurityRequirementValue) Reset() {
	*x = SecurityRequirement_SecurityRequirementValue{}
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityRequirement_SecurityRequirementValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityRequirement_SecurityRequirementValue) ProtoMessage() {}

func (x *SecurityRequirement_SecurityRequirementValue) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityRequirement_SecurityRequirementValue.ProtoReflect.Descriptor instead.
func (*SecurityRequirement_SecurityRequirementValue) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP(), []int{13, 0}
}

func (x *SecurityRequirement_SecurityRequirementValue) GetScope() []string {
	if x != nil {
		return x.Scope
	}
	return nil
}

var File_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto protoreflect.FileDescriptor

const file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDesc = "" +
	"\n" +
	"7grpc/gateway/protoc_gen_swagger/options/openapiv2.proto\x12'grpc.gateway.protoc_gen_swagger.options\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb8\b\n" +
	"\aSwagger\x12\x18\n" +
	"\aswagger\x18\x01 \x01(\tR\aswagger\x12A\n" +
	"\x04info\x18\x02 \x01(\v2-.grpc.gateway.protoc_gen_swagger.options.InfoR\x04info\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x1b\n" +
	"\tbase_path\x18\x04 \x01(\tR\bbasePath\x12X\n" +
	"\aschemes\x18\x05 \x03(\x0e2>.grpc.gateway.protoc_gen_swagger.options.Swagger.SwaggerSchemeR\aschemes\x12\x1a\n" +
	"\bconsumes\x18\x06 \x03(\tR\bconsumes\x12\x1a\n" +
	"\bproduces\x18\a \x03(\tR\bproduces\x12]\n" +
	"\tresponses\x18\n" +
	" \x03(\v2?.grpc.gateway.protoc_gen_swagger.options.Swagger.ResponsesEntryR\tresponses\x12o\n" +
	"\x14security_definitions\x18\v \x01(\v2<.grpc.gateway.protoc_gen_swagger.options.SecurityDefinitionsR\x13securityDefinitions\x12X\n" +
	"\bsecurity\x18\f \x03(\v2<.grpc.gateway.protoc_gen_swagger.options.SecurityRequirementR\bsecurity\x12c\n" +
	"\rexternal_docs\x18\x0e \x01(\v2>.grpc.gateway.protoc_gen_swagger.options.ExternalDocumentationR\fexternalDocs\x12`\n" +
	"\n" +
	"extensions\x18\x0f \x03(\v2@.grpc.gateway.protoc_gen_swagger.options.Swagger.ExtensionsEntryR\n" +
	"extensions\x1ao\n" +
	"\x0eResponsesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12G\n" +
	"\x05value\x18\x02 \x01(\v21.grpc.gateway.protoc_gen_swagger.options.ResponseR\x05value:\x028\x01\x1aU\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"B\n" +
	"\rSwaggerScheme\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04HTTP\x10\x01\x12\t\n" +
	"\x05HTTPS\x10\x02\x12\x06\n" +
	"\x02WS\x10\x03\x12\a\n" +
	"\x03WSS\x10\x04J\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"J\x04\b\r\x10\x0e\"\xc2\x06\n" +
	"\tOperation\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12c\n" +
	"\rexternal_docs\x18\x04 \x01(\v2>.grpc.gateway.protoc_gen_swagger.options.ExternalDocumentationR\fexternalDocs\x12!\n" +
	"\foperation_id\x18\x05 \x01(\tR\voperationId\x12\x1a\n" +
	"\bconsumes\x18\x06 \x03(\tR\bconsumes\x12\x1a\n" +
	"\bproduces\x18\a \x03(\tR\bproduces\x12_\n" +
	"\tresponses\x18\t \x03(\v2A.grpc.gateway.protoc_gen_swagger.options.Operation.ResponsesEntryR\tresponses\x12\x18\n" +
	"\aschemes\x18\n" +
	" \x03(\tR\aschemes\x12\x1e\n" +
	"\n" +
	"deprecated\x18\v \x01(\bR\n" +
	"deprecated\x12X\n" +
	"\bsecurity\x18\f \x03(\v2<.grpc.gateway.protoc_gen_swagger.options.SecurityRequirementR\bsecurity\x12b\n" +
	"\n" +
	"extensions\x18\r \x03(\v2B.grpc.gateway.protoc_gen_swagger.options.Operation.ExtensionsEntryR\n" +
	"extensions\x1ao\n" +
	"\x0eResponsesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12G\n" +
	"\x05value\x18\x02 \x01(\v21.grpc.gateway.protoc_gen_swagger.options.ResponseR\x05value:\x028\x01\x1aU\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01J\x04\b\b\x10\t\"\xd8\x01\n" +
	"\x06Header\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x18\n" +
	"\adefault\x18\x06 \x01(\tR\adefault\x12\x18\n" +
	"\apattern\x18\r \x01(\tR\apatternJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\a\x10\bJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"J\x04\b\n" +
	"\x10\vJ\x04\b\v\x10\fJ\x04\b\f\x10\rJ\x04\b\x0e\x10\x0fJ\x04\b\x0f\x10\x10J\x04\b\x10\x10\x11J\x04\b\x11\x10\x12J\x04\b\x12\x10\x13\"\x90\x05\n" +
	"\bResponse\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12G\n" +
	"\x06schema\x18\x02 \x01(\v2/.grpc.gateway.protoc_gen_swagger.options.SchemaR\x06schema\x12X\n" +
	"\aheaders\x18\x03 \x03(\v2>.grpc.gateway.protoc_gen_swagger.options.Response.HeadersEntryR\aheaders\x12[\n" +
	"\bexamples\x18\x04 \x03(\v2?.grpc.gateway.protoc_gen_swagger.options.Response.ExamplesEntryR\bexamples\x12a\n" +
	"\n" +
	"extensions\x18\x05 \x03(\v2A.grpc.gateway.protoc_gen_swagger.options.Response.ExtensionsEntryR\n" +
	"extensions\x1ak\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12E\n" +
	"\x05value\x18\x02 \x01(\v2/.grpc.gateway.protoc_gen_swagger.options.HeaderR\x05value:\x028\x01\x1a;\n" +
	"\rExamplesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aU\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xd0\x03\n" +
	"\x04Info\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12(\n" +
	"\x10terms_of_service\x18\x03 \x01(\tR\x0etermsOfService\x12J\n" +
	"\acontact\x18\x04 \x01(\v20.grpc.gateway.protoc_gen_swagger.options.ContactR\acontact\x12J\n" +
	"\alicense\x18\x05 \x01(\v20.grpc.gateway.protoc_gen_swagger.options.LicenseR\alicense\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12]\n" +
	"\n" +
	"extensions\x18\a \x03(\v2=.grpc.gateway.protoc_gen_swagger.options.Info.ExtensionsEntryR\n" +
	"extensions\x1aU\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"E\n" +
	"\aContact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"/\n" +
	"\aLicense\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"K\n" +
	"\x15ExternalDocumentation\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\xe7\x02\n" +
	"\x06Schema\x12T\n" +
	"\vjson_schema\x18\x01 \x01(\v23.grpc.gateway.protoc_gen_swagger.options.JSONSchemaR\n" +
	"jsonSchema\x12$\n" +
	"\rdiscriminator\x18\x02 \x01(\tR\rdiscriminator\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\x12c\n" +
	"\rexternal_docs\x18\x05 \x01(\v2>.grpc.gateway.protoc_gen_swagger.options.ExternalDocumentationR\fexternalDocs\x122\n" +
	"\aexample\x18\x06 \x01(\v2\x14.google.protobuf.AnyB\x02\x18\x01R\aexample\x12%\n" +
	"\x0eexample_string\x18\a \x01(\tR\rexampleStringJ\x04\b\x04\x10\x05\"\xdd\a\n" +
	"\n" +
	"JSONSchema\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x18\n" +
	"\adefault\x18\a \x01(\tR\adefault\x12\x1b\n" +
	"\tread_only\x18\b \x01(\bR\breadOnly\x12\x18\n" +
	"\aexample\x18\t \x01(\tR\aexample\x12\x1f\n" +
	"\vmultiple_of\x18\n" +
	" \x01(\x01R\n" +
	"multipleOf\x12\x18\n" +
	"\amaximum\x18\v \x01(\x01R\amaximum\x12+\n" +
	"\x11exclusive_maximum\x18\f \x01(\bR\x10exclusiveMaximum\x12\x18\n" +
	"\aminimum\x18\r \x01(\x01R\aminimum\x12+\n" +
	"\x11exclusive_minimum\x18\x0e \x01(\bR\x10exclusiveMinimum\x12\x1d\n" +
	"\n" +
	"max_length\x18\x0f \x01(\x04R\tmaxLength\x12\x1d\n" +
	"\n" +
	"min_length\x18\x10 \x01(\x04R\tminLength\x12\x18\n" +
	"\apattern\x18\x11 \x01(\tR\apattern\x12\x1b\n" +
	"\tmax_items\x18\x14 \x01(\x04R\bmaxItems\x12\x1b\n" +
	"\tmin_items\x18\x15 \x01(\x04R\bminItems\x12!\n" +
	"\funique_items\x18\x16 \x01(\bR\vuniqueItems\x12%\n" +
	"\x0emax_properties\x18\x18 \x01(\x04R\rmaxProperties\x12%\n" +
	"\x0emin_properties\x18\x19 \x01(\x04R\rminProperties\x12\x1a\n" +
	"\brequired\x18\x1a \x03(\tR\brequired\x12\x14\n" +
	"\x05array\x18\" \x03(\tR\x05array\x12]\n" +
	"\x04type\x18# \x03(\x0e2I.grpc.gateway.protoc_gen_swagger.options.JSONSchema.JSONSchemaSimpleTypesR\x04type\x12\x16\n" +
	"\x06format\x18$ \x01(\tR\x06format\x12\x12\n" +
	"\x04enum\x18. \x03(\tR\x04enum\"w\n" +
	"\x15JSONSchemaSimpleTypes\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05ARRAY\x10\x01\x12\v\n" +
	"\aBOOLEAN\x10\x02\x12\v\n" +
	"\aINTEGER\x10\x03\x12\b\n" +
	"\x04NULL\x10\x04\x12\n" +
	"\n" +
	"\x06NUMBER\x10\x05\x12\n" +
	"\n" +
	"\x06OBJECT\x10\x06\x12\n" +
	"\n" +
	"\x06STRING\x10\aJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x04\x10\x05J\x04\b\x12\x10\x13J\x04\b\x13\x10\x14J\x04\b\x17\x10\x18J\x04\b\x1b\x10\x1cJ\x04\b\x1c\x10\x1dJ\x04\b\x1d\x10\x1eJ\x04\b\x1e\x10\"J\x04\b%\x10*J\x04\b*\x10+J\x04\b+\x10.\"\x92\x01\n" +
	"\x03Tag\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12c\n" +
	"\rexternal_docs\x18\x03 \x01(\v2>.grpc.gateway.protoc_gen_swagger.options.ExternalDocumentationR\fexternalDocsJ\x04\b\x01\x10\x02\"\xf3\x01\n" +
	"\x13SecurityDefinitions\x12f\n" +
	"\bsecurity\x18\x01 \x03(\v2J.grpc.gateway.protoc_gen_swagger.options.SecurityDefinitions.SecurityEntryR\bsecurity\x1at\n" +
	"\rSecurityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12M\n" +
	"\x05value\x18\x02 \x01(\v27.grpc.gateway.protoc_gen_swagger.options.SecuritySchemeR\x05value:\x028\x01\"\xf5\x06\n" +
	"\x0eSecurityScheme\x12P\n" +
	"\x04type\x18\x01 \x01(\x0e2<.grpc.gateway.protoc_gen_swagger.options.SecurityScheme.TypeR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12J\n" +
	"\x02in\x18\x04 \x01(\x0e2:.grpc.gateway.protoc_gen_swagger.options.SecurityScheme.InR\x02in\x12P\n" +
	"\x04flow\x18\x05 \x01(\x0e2<.grpc.gateway.protoc_gen_swagger.options.SecurityScheme.FlowR\x04flow\x12+\n" +
	"\x11authorization_url\x18\x06 \x01(\tR\x10authorizationUrl\x12\x1b\n" +
	"\ttoken_url\x18\a \x01(\tR\btokenUrl\x12G\n" +
	"\x06scopes\x18\b \x01(\v2/.grpc.gateway.protoc_gen_swagger.options.ScopesR\x06scopes\x12g\n" +
	"\n" +
	"extensions\x18\t \x03(\v2G.grpc.gateway.protoc_gen_swagger.options.SecurityScheme.ExtensionsEntryR\n" +
	"extensions\x1aU\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"K\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_INVALID\x10\x00\x12\x0e\n" +
	"\n" +
	"TYPE_BASIC\x10\x01\x12\x10\n" +
	"\fTYPE_API_KEY\x10\x02\x12\x0f\n" +
	"\vTYPE_OAUTH2\x10\x03\"1\n" +
	"\x02In\x12\x0e\n" +
	"\n" +
	"IN_INVALID\x10\x00\x12\f\n" +
	"\bIN_QUERY\x10\x01\x12\r\n" +
	"\tIN_HEADER\x10\x02\"j\n" +
	"\x04Flow\x12\x10\n" +
	"\fFLOW_INVALID\x10\x00\x12\x11\n" +
	"\rFLOW_IMPLICIT\x10\x01\x12\x11\n" +
	"\rFLOW_PASSWORD\x10\x02\x12\x14\n" +
	"\x10FLOW_APPLICATION\x10\x03\x12\x14\n" +
	"\x10FLOW_ACCESS_CODE\x10\x04\"\xf2\x02\n" +
	"\x13SecurityRequirement\x12\x88\x01\n" +
	"\x14security_requirement\x18\x01 \x03(\v2U.grpc.gateway.protoc_gen_swagger.options.SecurityRequirement.SecurityRequirementEntryR\x13securityRequirement\x1a0\n" +
	"\x18SecurityRequirementValue\x12\x14\n" +
	"\x05scope\x18\x01 \x03(\tR\x05scope\x1a\x9d\x01\n" +
	"\x18SecurityRequirementEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12k\n" +
	"\x05value\x18\x02 \x01(\v2U.grpc.gateway.protoc_gen_swagger.options.SecurityRequirement.SecurityRequirementValueR\x05value:\x028\x01\"\x94\x01\n" +
	"\x06Scopes\x12P\n" +
	"\x05scope\x18\x01 \x03(\v2:.grpc.gateway.protoc_gen_swagger.options.Scopes.ScopeEntryR\x05scope\x1a8\n" +
	"\n" +
	"ScopeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BCZAgithub.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/optionsb\x06proto3"

var (
	file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescOnce sync.Once
	file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescData []byte
)

func file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescGZIP() []byte {
	file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescOnce.Do(func() {
		file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDesc), len(file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDesc)))
	})
	return file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDescData
}

var file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_goTypes = []any{
	(Swagger_SwaggerScheme)(0),            // 0: grpc.gateway.protoc_gen_swagger.options.Swagger.SwaggerScheme
	(JSONSchema_JSONSchemaSimpleTypes)(0), // 1: grpc.gateway.protoc_gen_swagger.options.JSONSchema.JSONSchemaSimpleTypes
	(SecurityScheme_Type)(0),              // 2: grpc.gateway.protoc_gen_swagger.options.SecurityScheme.Type
	(SecurityScheme_In)(0),                // 3: grpc.gateway.protoc_gen_swagger.options.SecurityScheme.In
	(SecurityScheme_Flow)(0),              // 4: grpc.gateway.protoc_gen_swagger.options.SecurityScheme.Flow
	(*Swagger)(nil),                       // 5: grpc.gateway.protoc_gen_swagger.options.Swagger
	(*Operation)(nil),                     // 6: grpc.gateway.protoc_gen_swagger.options.Operation
	(*Header)(nil),                        // 7: grpc.gateway.protoc_gen_swagger.options.Header
	(*Response)(nil),                      // 8: grpc.gateway.protoc_gen_swagger.options.Response
	(*Info)(nil),                          // 9: grpc.gateway.protoc_gen_swagger.options.Info
	(*Contact)(nil),                       // 10: grpc.gateway.protoc_gen_swagger.options.Contact
	(*License)(nil),                       // 11: grpc.gateway.protoc_gen_swagger.options.License
	(*ExternalDocumentation)(nil),         // 12: grpc.gateway.protoc_gen_swagger.options.ExternalDocumentation
	(*Schema)(nil),                        // 13: grpc.gateway.protoc_gen_swagger.options.Schema
	(*JSONSchema)(nil),                    // 14: grpc.gateway.protoc_gen_swagger.options.JSONSchema
	(*Tag)(nil),                           // 15: grpc.gateway.protoc_gen_swagger.options.Tag
	(*SecurityDefinitions)(nil),           // 16: grpc.gateway.protoc_gen_swagger.options.SecurityDefinitions
	(*SecurityScheme)(nil),                // 17: grpc.gateway.protoc_gen_swagger.options.SecurityScheme
	(*SecurityRequirement)(nil),           // 18: grpc.gateway.protoc_gen_swagger.options.SecurityRequirement
	(*Scopes)(nil),                        // 19: grpc.gateway.protoc_gen_swagger.options.Scopes
	nil,                                   // 20: grpc.gateway.protoc_gen_swagger.options.Swagger.ResponsesEntry
	nil,                                   // 21: grpc.gateway.protoc_gen_swagger.options.Swagger.ExtensionsEntry
	nil,                                   // 22: grpc.gateway.protoc_gen_swagger.options.Operation.ResponsesEntry
	nil,                                   // 23: grpc.gateway.protoc_gen_swagger.options.Operation.ExtensionsEntry
	nil,                                   // 24: grpc.gateway.protoc_gen_swagger.options.Response.HeadersEntry
	nil,                                   // 25: grpc.gateway.protoc_gen_swagger.options.Response.ExamplesEntry
	nil,                                   // 26: grpc.gateway.protoc_gen_swagger.options.Response.ExtensionsEntry
	nil,                                   // 27: grpc.gateway.protoc_gen_swagger.options.Info.ExtensionsEntry
	nil,                                   // 28: grpc.gateway.protoc_gen_swagger.options.SecurityDefinitions.SecurityEntry
	nil,                                   // 29: grpc.gateway.protoc_gen_swagger.options.SecurityScheme.ExtensionsEntry
	(*SecurityRequirement_SecurityRequirementValue)(nil), // 30: grpc.gateway.protoc_gen_swagger.options.SecurityRequirement.SecurityRequirementValue
	nil,                    // 31: grpc.gateway.protoc_gen_swagger.options.SecurityRequirement.SecurityRequirementEntry
	nil,                    // 32: grpc.gateway.protoc_gen_swagger.options.Scopes.ScopeEntry
	(*anypb.Any)(nil),      // 33: google.protobuf.Any
	(*structpb.Value)(nil), // 34: google.protobuf.Value
}
var file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_depIdxs = []int32{
	9,  // 0: grpc.gateway.protoc_gen_swagger.options.Swagger.info:type_name -> grpc.gateway.protoc_gen_swagger.options.Info
	0,  // 1: grpc.gateway.protoc_gen_swagger.options.Swagger.schemes:type_name -> grpc.gateway.protoc_gen_swagger.options.Swagger.SwaggerScheme
	20, // 2: grpc.gateway.protoc_gen_swagger.options.Swagger.responses:type_name -> grpc.gateway.protoc_gen_swagger.options.Swagger.ResponsesEntry
	16, // 3: grpc.gateway.protoc_gen_swagger.options.Swagger.security_definitions:type_name -> grpc.gateway.protoc_gen_swagger.options.SecurityDefinitions
	18, // 4: grpc.gateway.protoc_gen_swagger.options.Swagger.security:type_name -> grpc.gateway.protoc_gen_swagger.options.SecurityRequirement
	12, // 5: grpc.gateway.protoc_gen_swagger.options.Swagger.external_docs:type_name -> grpc.gateway.protoc_gen_swagger.options.ExternalDocumentation
	21, // 6: grpc.gateway.protoc_gen_swagger.options.Swagger.extensions:type_name -> grpc.gateway.protoc_gen_swagger.options.Swagger.ExtensionsEntry
	12, // 7: grpc.gateway.protoc_gen_swagger.options.Operation.external_docs:type_name -> grpc.gateway.protoc_gen_swagger.options.ExternalDocumentation
	22, // 8: grpc.gateway.protoc_gen_swagger.options.Operation.responses:type_name -> grpc.gateway.protoc_gen_swagger.options.Operation.ResponsesEntry
	18, // 9: grpc.gateway.protoc_gen_swagger.options.Operation.security:type_name -> grpc.gateway.protoc_gen_swagger.options.SecurityRequirement
	23, // 10: grpc.gateway.protoc_gen_swagger.options.Operation.extensions:type_name -> grpc.gateway.protoc_gen_swagger.options.Operation.ExtensionsEntry
	13, // 11: grpc.gateway.protoc_gen_swagger.options.Response.schema:type_name -> grpc.gateway.protoc_gen_swagger.options.Schema
	24, // 12: grpc.gateway.protoc_gen_swagger.options.Response.headers:type_name -> grpc.gateway.protoc_gen_swagger.options.Response.HeadersEntry
	25, // 13: grpc.gateway.protoc_gen_swagger.options.Response.examples:type_name -> grpc.gateway.protoc_gen_swagger.options.Response.ExamplesEntry
	26, // 14: grpc.gateway.protoc_gen_swagger.options.Response.extensions:type_name -> grpc.gateway.protoc_gen_swagger.options.Response.ExtensionsEntry
	10, // 15: grpc.gateway.protoc_gen_swagger.options.Info.contact:type_name -> grpc.gateway.protoc_gen_swagger.options.Contact
	11, // 16: grpc.gateway.protoc_gen_swagger.options.Info.license:type_name -> grpc.gateway.protoc_gen_swagger.options.License
	27, // 17: grpc.gateway.protoc_gen_swagger.options.Info.extensions:type_name -> grpc.gateway.protoc_gen_swagger.options.Info.ExtensionsEntry
	14, // 18: grpc.gateway.protoc_gen_swagger.options.Schema.json_schema:type_name -> grpc.gateway.protoc_gen_swagger.options.JSONSchema
	12, // 19: grpc.gateway.protoc_gen_swagger.options.Schema.external_docs:type_name -> grpc.gateway.protoc_gen_swagger.options.ExternalDocumentation
	33, // 20: grpc.gateway.protoc_gen_swagger.options.Schema.example:type_name -> google.protobuf.Any
	1,  // 21: grpc.gateway.protoc_gen_swagger.options.JSONSchema.type:type_name -> grpc.gateway.protoc_gen_swagger.options.JSONSchema.JSONSchemaSimpleTypes
	12, // 22: grpc.gateway.protoc_gen_swagger.options.Tag.external_docs:type_name -> grpc.gateway.protoc_gen_swagger.options.ExternalDocumentation
	28, // 23: grpc.gateway.protoc_gen_swagger.options.SecurityDefinitions.security:type_name -> grpc.gateway.protoc_gen_swagger.options.SecurityDefinitions.SecurityEntry
	2,  // 24: grpc.gateway.protoc_gen_swagger.options.SecurityScheme.type:type_name -> grpc.gateway.protoc_gen_swagger.options.SecurityScheme.Type
	3,  // 25: grpc.gateway.protoc_gen_swagger.options.SecurityScheme.in:type_name -> grpc.gateway.protoc_gen_swagger.options.SecurityScheme.In
	4,  // 26: grpc.gateway.protoc_gen_swagger.options.SecurityScheme.flow:type_name -> grpc.gateway.protoc_gen_swagger.options.SecurityScheme.Flow
	19, // 27: grpc.gateway.protoc_gen_swagger.options.SecurityScheme.scopes:type_name -> grpc.gateway.protoc_gen_swagger.options.Scopes
	29, // 28: grpc.gateway.protoc_gen_swagger.options.SecurityScheme.extensions:type_name -> grpc.gateway.protoc_gen_swagger.options.SecurityScheme.ExtensionsEntry
	31, // 29: grpc.gateway.protoc_gen_swagger.options.SecurityRequirement.security_requirement:type_name -> grpc.gateway.protoc_gen_swagger.options.SecurityRequirement.SecurityRequirementEntry
	32, // 30: grpc.gateway.protoc_gen_swagger.options.Scopes.scope:type_name -> grpc.gateway.protoc_gen_swagger.options.Scopes.ScopeEntry
	8,  // 31: grpc.gateway.protoc_gen_swagger.options.Swagger.ResponsesEntry.value:type_name -> grpc.gateway.protoc_gen_swagger.options.Response
	34, // 32: grpc.gateway.protoc_gen_swagger.options.Swagger.ExtensionsEntry.value:type_name -> google.protobuf.Value
	8,  // 33: grpc.gateway.protoc_gen_swagger.options.Operation.ResponsesEntry.value:type_name -> grpc.gateway.protoc_gen_swagger.options.Response
	34, // 34: grpc.gateway.protoc_gen_swagger.options.Operation.ExtensionsEntry.value:type_name -> google.protobuf.Value
	7,  // 35: grpc.gateway.protoc_gen_swagger.options.Response.HeadersEntry.value:type_name -> grpc.gateway.protoc_gen_swagger.options.Header
	34, // 36: grpc.gateway.protoc_gen_swagger.options.Response.ExtensionsEntry.value:type_name -> google.protobuf.Value
	34, // 37: grpc.gateway.protoc_gen_swagger.options.Info.ExtensionsEntry.value:type_name -> google.protobuf.Value
	17, // 38: grpc.gateway.protoc_gen_swagger.options.SecurityDefinitions.SecurityEntry.value:type_name -> grpc.gateway.protoc_gen_swagger.options.SecurityScheme
	34, // 39: grpc.gateway.protoc_gen_swagger.options.SecurityScheme.ExtensionsEntry.value:type_name -> google.protobuf.Value
	30, // 40: grpc.gateway.protoc_gen_swagger.options.SecurityRequirement.SecurityRequirementEntry.value:type_name -> grpc.gateway.protoc_gen_swagger.options.SecurityRequirement.SecurityRequirementValue
	41, // [41:41] is the sub-list for method output_type
	41, // [41:41] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_init() }
func file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_init() {
	if File_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDesc), len(file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_goTypes,
		DependencyIndexes: file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_depIdxs,
		EnumInfos:         file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_enumTypes,
		MessageInfos:      file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_msgTypes,
	}.Build()
	File_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto = out.File
	file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_goTypes = nil
	file_grpc_gateway_protoc_gen_swagger_options_openapiv2_proto_depIdxs = nil
}
