name: build
on: 
  push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.25
      uses: actions/setup-go@v5
      with:
        go-version: "1.25"
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        args: -D protogetter

    - name: Build
      run: make test
    
    - name: Publish Codecoverage report
      run: bash <(curl -s https://codecov.io/bash)
